### ISSUE TITLE
Rename DayOfWeek to Weekday

### ISSUE THREAD

**Issue by luolong** [luolong/ceylon.time#16]
The name of type DayOfWeek is a bit verbose and much too technical for what is means.

Weekday is much simpler name for this type.

**Comment by DiegoCoronel** [comment]
in progress

**Comment by tombentley** [comment]
Fwiw "Weekday" to me means Monday to Friday, not a weekend.

**Comment by DiegoCoronel** [comment]
you are right but another languages use this nomenclature.. Python, ruby ,
etc.... Ill talk with roland about it.
Em 19/02/2013 02:34, "Tom Bentley" notifications@github.com escreveu:

**Comment by gavinking** [comment]
> Fwiw "Weekday" to me means Monday to Friday, not a weekend.

To me too.

**Comment by luolong** [comment]
Khmm... 
Online dictionaries seem to agree with you.
Being non-native English speaker I really did not see it that way.

Just to check how other languages have named day of week in their calendar libraries I turned to [Rosetta Code](http://rosettacode.org/wiki/Day_of_the_week).

It seems that either "DayOfWeek" (or some variant of it) and "Weekday" is used pretty interchangeably. 
Few languages use simply "Day", but I would not go there/ much too ambiguous for my tastes.

**Comment by gavinking** [comment]
FTR, if someone asked me "what day is it?" I would immediately answer "Tuesday".

If someone asked me "what weekday is it?" I would understand what they I were asking, and I would also immediately know that English is not their first language ;-)

**Comment by luolong** [comment]
Point well taken.

So let's just rename this back to DayOfWeek then and rename fields on Date:

```
shared Integer date; // day of month value
shared DayOfWeek day; // day of the week
```

We'd probably have to rename methods on DateTime type that return date-only and time-only versions of themselves as well for this change.

**Comment by tombentley** [comment]
Personally I don't see what's so wrong with `DayOfWeek`. It's completely unambiguous which is helpful when reading code outside an IDE. It _is_ a little less guessable writing code and you forget (as I often do) that there's also `dayOfMonth`, and possibly `dayOfYear`, but the IDE will presumably be suggesting those as fixes, so I don't see that as a big deal.

**Comment by luolong** [comment]
I personally find field names like `dayOfWeek` and `dayOfMonth` a bit mouthful. It also promotes names like `monthOfYear` and `hourOfDay` and `minuteOfHour`, etc. 

Technically speaking there's nothing wrong with those (and at some point I had the naming convention for the date and time fields laid out exactly like this) but after using them for a while they kind of started to annoy me a whole lot.

I guess it felt like stating the obvious all the time.

**Comment by tombentley** [comment]
They _are_ a bit of a mouthful, but at least in the case of `dayOfWeek`/`dayOfMonth` I personally think it's worth it to avoid ambiguity. I don't think the same is true of `minuteOfHour` (etc.) because I can't recall ever having meant any other kind of minute.

I'd like to hear what others think.

**Comment by DiegoCoronel** [comment]
For brazilians, day is like the number and date is like "day, month and
year". to know if its sunday, monday, etc. we ask: "Qual o dia da semana ?"
thats is in english: What day of week ?

2013/2/19 Tom Bentley notifications@github.com

**Comment by tombentley** [comment]
@DiegoCoronel in Britain:
- "What day is it?" would mean you want the day of the week.
- "What is the date?" usually means you want to know the day of the month
- But generally talking about "the date" can mean either "day of the month" or the full day/month/year. 

So "date" is ambiguous and "day" means something different to me than it does to you.

**Comment by luolong** [comment]
We can't really make the api itself internationalizable (well, not easily any way), so we must settle on some sane naming.

I can easily live with `dayOfWeek` as a field name for, well _day of week_.
I really dislike the `dayOfMonth` though. 

It is bound to be highly used field and in the context of the Date object, I hardly see an ambiguity there:

```
value birthday = ...
println("Birthday: `` birthday.month `` `` birthday.date ``.");
```

versus

```
println("Birthday: `` birthday.month `` `` birthday.dayOfMonth ``.");
```

**Comment by gavinking** [comment]
I'm perfectly happy if `day` means the day of the month, and `dayOfWeek` means the day of the week.

**Comment by DiegoCoronel** [comment]
i vote for this also --> I'm perfectly happy if day means the day of the
month, and dayOfWeek means the day of the week.

2013/2/19 Gavin King notifications@github.com
