### ISSUE TITLE
Support for Interval

### ISSUE THREAD

**Issue by DiegoCoronel** [luolong/ceylon.time#21]
Currently we do not have any way to express interval between two dates. Operations are useful in everyday life that we can express through this feature, for example:

``` ceylon
    Date myFirstDay = date(2013, november,1);
    Interval myVacations = Interval( firstDay, myFirstDay.plusDays(15) ); 

    Date wifeFirstDay = date(2013, october, 26);
    Interval wifeVacations = Interval( wifeFirstDay, wifeFirstDay.plusDays(30) ); 

    Interval together = myVacations.overlaps( wifeVacations );

    print("Our days together " together.duration.period "");
```

Ps.: Ok, i know i could have a better sample with finances :)

Where we can receive in constructor something like: 

``` ceylon
    shared class Interval( start, end ) {

    ReadableInstant start;
    ReadableInstant|ReadableDuration|ReadablePeriod end;
```
- in case above maybe we need to have ReadableInstant in date and dateTime interfaces...
- Does it make sense for Time ?

for fields we could have:
- start
- end
- duration

important feature we could have:
- shared Interval overlap({ReadableInterval*})

**Comment by luolong** [comment]
Interval you speak of - it is something like range, right?

All of the useful types of intervals I can think of are usually bound to a specific date/time type:

```
Interval<Date> vacation = Interval( date(2013, february, 25), date(2013, march, 1) );
Interval<DateTime> meeting = Interval( today().at(14, 30) .. today().at(16, 00) );
Interval<Time> lunchBreak = Interval( time(12, 00) ... time(13, 00) );
```

So my guess is that we should parametrize the Interval type on the Readable\* date/time types:

```
shares interface Interval<Kind>
           given Kind satisfies ReadableInstant | ReadableDate | ReadableTime 
               | ReadableDateTime | ReadableZoneDateTime { }
```

(or something very similar)

Some of the useful features of Interval should be:

**getting start and end of the interval:**

```
shared interface Interval<Kind> ... {
    shared formal Kind start;
    shared formal Kind end;
}
```

**getting duration of the Interval in milliseconds:**

```
shared formal Duration duration;
```

**getting period of the interval between _start_ and _end_**

```
shared formal Period period;
```

**checking if particular value falls into the interval:**

```
shared formal Boolean contains(Kind value);
```

**checking if two Intervals overlap and getting an intersection of those**

```
shared formal Boolean overlaps(Interval<Kind> other );
shared formal Interval<Kind> intersection( Interval<Kind> other );
```

**It must be Iterable:**

```
shared formal Iterator<Kind> iterator
```

Some of this can be actually achieved with the _native_ `Range` type. Some of this is specific to date/time.

**Comment by DiegoCoronel** [comment]
Currently im playing with it and i have

``` ceylon
shared interface Interval<Kind> satisfies Ranged<Kind, [Kind*]> 
                                given Kind satisfies Comparable<Kind> & Ordinal<Kind> {

    shared formal Kind start;
    shared formal Kind end;
    shared formal Duration duration;

    "...inclusive..."
    shared formal Interval<Kind>? overlap( Interval<Kind> other );

    "...exclusive..."
    shared formal Interval<Kind>? gap( Interval<Kind> other );

}

```

Where just this interface is exposed to user and the implementations are called from Date/DateTime/Time/Instant instances... something like: `today.to( anyDay() )`

**Comment by DiegoCoronel** [comment]
discussion moved for: https://github.com/ceylon/ceylon-sdk/issues/60

**Comment by DiegoCoronel** [comment]
This is done.

**Comment by gavinking** [comment]
:-)
