### ISSUE TITLE
Merge calendar calculations

### ISSUE THREAD

**Issue by DiegoCoronel** [luolong/ceylon.time#23]
Currently we have 2 files using calendar calculations: ceylon.tim.impl.utils.ceylon and ceylon.time.math.functions, we need to merge them. My vote is to put all this in ceylon.time.math.functions and do something 

``` ceylon
doc "Utility class for common functions for calendar related calculations"
shared object calendarMath{ }
```

**Comment by luolong** [comment]
Yes, I agree

**Comment by DiegoCoronel** [comment]
in progress
