### ISSUE TITLE
WithDay method should throw exception?

### ISSUE THREAD

**Issue by DiegoCoronel** [luolong/ceylon.time#25]
Currently we dont have any kind of check to this situation:

``` ceylon
    date(1982, december,13).withDay(0);
    date(1982, december,13).withDay(40);
```

**Comment by DiegoCoronel** [comment]
for cases where the value <= 0 `date(1982, december,13).withDay(0);` 
we have this result: `date( 1982, 11, 30 )`

for cases where the value is > last day of month `date(1982, december,13).withDay(40);` 
we have `date( 1982, december, 31)`, is this the expected behavior we want?

**Comment by luolong** [comment]
I think, as initial behavior this is quite acceptable. 

Further down the road we would probably want to be able to provide a  resolution strategy along with these mutation methods. 

Another thing to consider: what should happen if I do this:

```
date(31, january, 2013).withMonth(february);
```

**Comment by DiegoCoronel** [comment]
i agree, maybe we could just improve when value is <= 0 to  consider it as first day of month, what do you think ?

**Comment by DiegoCoronel** [comment]
So, if we have `date(1982, december,13).withDay(40);` like `1982-12-31` then we need same behavior for day less than or equal to 0. With above fix now `date(1982, december,13).withDay(0);` results in `1982-12-01`

**Comment by luolong** [comment]
Thinking about this for a while, I do not think we should be silently "fixing" the invalid dates if the input is clearly not valid for the given date.

That is -  calling `date.withDay(40)` on any date is plainly wrong and should throw an exception. (I used 40 here for illustrating a case where given date is clearly out of valid bounds)

same goes to `date.withDay(n)` where `n <= 0`.

More troublesome is the issue of invalid dates that come from setting a month or a year.

That is if somebody does something equivalent of `date(31, december, 2013).withMonth(february)` (or `date(29, february, 2012).withYear(2007)`), should it throw an exception?

I think that for the sake of consistency and for the element of least surprise, all of these cases should throw an exception.

Later on, we can add support for _resolution strategy_, that will allow to customize this behavior.

**Comment by DiegoCoronel** [comment]
And i believe we want same behavior for time... right ?

**Comment by DiegoCoronel** [comment]
im having problems with merge.. soon ill do the request again
